// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgqlgjsmkunodveetgsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBncWxnanNta3Vub2R2ZWV0Z3N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDcxNzcsImV4cCI6MjA2OTIyMzE3N30.gtwouYl-0oJJiGtDnklMduLlo-KOxVoZLk8prGnSNNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});